# yourspotify.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: yourspotify

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourspotify-deployment
  namespace: yourspotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourspotify
  template:
    metadata:
      labels:
        app: yourspotify
    spec:
      containers:
        - name: yourspotify-client
          image: yooooomi/your_spotify_client:1.7.3
          env:
            - name: API_ENDPOINT
              value: https://yourspotify-backend.k8s.thinkbox.center
          ports:
            - containerPort: 3000

        - name: yourspotify-server
          image: yooooomi/your_spotify_server:1.7.3
          env:
            - name: API_ENDPOINT
              value: https://yourspotify-backend.k8s.thinkbox.center
            - name: CLIENT_ENDPOINT
              value: https://yourspotify.k8s.thinkbox.center
            - name: CORS
              value: https://yourspotify.k8s.thinkbox.center, https://yourspotify-backend.k8s.thinkbox.center
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: yourspotify-secrets
                  key: spotify_public
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yourspotify-secrets
                  key: spotify_secret
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: yourspotify-secrets
  namespace: yourspotify
type: Opaque
stringData:
  spotify_public: "<spotify-application-client-id>"
  spotify_secret: "<spotify-application-client-secret>"

---
apiVersion: v1
kind: Service
metadata:
  name: yourspotify
  namespace: yourspotify
spec:
  selector:
    app: yourspotify
  ports:
    - name: yourspotify-client
      port: 3000
    - name: yourspotify-server
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yourspotify-ingress
  namespace: yourspotify
spec:
  rules:
    - host: yourspotify.k8s.thinkbox.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yourspotify
                port:
                  number: 3000

    - host: yourspotify-backend.k8s.thinkbox.center
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yourspotify
                port:
                  number: 8080
